### ISSUE TITLE
Failed to activate the impress package

### ISSUE THREAD

**Issue by ayonafamily** [kaitoy/impress#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [impress](https://github.com/kaitoy/impress) package 0.1.1

### Stack Trace

Failed to activate the impress package

```
At ENOENT: no such file or directory, open 'impress/icons/x-mark.png'

Error: ENOENT: no such file or directory, open 'impress/icons/x-mark.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Object.exports.readIconInBase64 (/packages/impress/lib/util.coffee:48:6)
    at /packages/impress/lib/step-list.js:14:20)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/impress/lib/step-list-view.coffee:8:12)
    at /packages/impress/lib/step-list-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/impress/lib/step-list-view-manager.coffee:3:16)
    at /packages/impress/lib/step-list-view-manager.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 0.9.0 
atom-beautify 0.29.12 
atom-ja-dummy 0.2.0 
atom-lorempixel 0.1.0 
atom-material-syntax 0.4.6 
atom-material-ui 1.3.6 
color-picker 2.2.2 
emmet 2.4.3 
file-icons 1.7.19 
file-type-icons 1.3.2 
highlight-line 0.11.1 
impress 0.1.1 
linter 1.11.16 
lipsum 0.1.0 
minimap 4.25.0 
monokai-complete-syntax 0.2.3 
seti-ui 1.3.2 
Writer 0.1.0 
```

**Comment by kaitoy** [comment]
I will take a look at it this weekend.

**Comment by kaitoy** [comment]
I couldn't reproduce it with Atom 1.14.4 x64 and impress package 0.1.1 on Windows 7.
Does `impress/icons/x-mark.png` exist on your environment?
Could you try uninstall and reinstall the package?

**Comment by ayonafamily** [comment]
Ok! I will do it.

2017-03-05 12:55 GMT-05:00, Kaito Yamada <notifications@github.com>:
> I couldn't reproduce it with Atom 1.14.4 x64 and impress package 0.1.1 on
> Windows 7.
> Does `impress/icons/x-mark.png` exist on your environment?
> Could you try uninstall and reinstall the package?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kaitoy/impress/issues/2#issuecomment-284247110


-- 
Dios no pone límites a la fe; la fe no pone límites a Dios

**Comment by paxelito** [comment]
Same issue for me on Ubuntu 16.04
